export default {
	FETCH_HEROES            : 'FETCH_HEROES',
	FETCH_HEROES_RESULT     : 'FETCH_HEROES_RESULT',
	BOOKMARK_HERO           : 'BOOKMARK_HERO',
	UPDATE_HERO             : 'UPDATE_HERO',
	FETCH_BOOKMARKED_HEROES : 'GET_BOOKMARKED_HEROES',
};

